application: appjinja
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /styles/styles\.css
  static_files: styles/styles.css
  upload: styles/styles\.css

- url: /img(.*\.(gif|png|jpg|ico|js|css|php|xml))
  static_files: img\1
  upload: img(.*\.(gif|png|jpg|ico|js|css|php|xml))

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
